services:
  csrf:
    build: ./csrf
    container_name: csrf
    networks:
      - caddy_network
  
  phishing:
    build: ./phishing
    container_name: phishing
    networks:
      - caddy_network
  
  caddy:
    build: .
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./caddy_data:/data            # Persistent storage for certificates
      - ./caddy_config:/config        # Persistent storage for configurations
    networks:
      - caddy_network
    depends_on:
      - csrf
      - phishing

  dnsmasq:
    image: 4km3/dnsmasq
    container_name: dnsmasq
    restart: unless-stopped
    ports:
      - "53:53/udp"
      - "53:53/tcp"
    volumes:
      - ./dnsmasq.conf:/etc/dnsmasq.conf
    networks:
      - caddy_network

networks:
  caddy_network:
    driver: bridge