services:
  csrf:
    build: ./csrf
    container_name: csrf
    networks:
      - caddy_network
  
  phishing:
    build: ./phishing
    container_name: phishing
    networks:
      - caddy_network
  
  caddy:
    image: caddy:2
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./caddy_data:/data            # Persistent storage for certificates
      - ./caddy_config:/config        # Persistent storage for configurations
    networks:
      - caddy_network
    depends_on:
      - csrf
      - phishing

networks:
  caddy_network:
    driver: bridge